export const importedUsers = [{
  appIdentifier: 'com.littleswaps',
  badgeCount: 0,
  createdAt: 1737139817,
  email: 'philipleesha@gmail.com',
  firstName: 'Philip',
  lastName: 'Leesha',
  lastOnlineTimestamp: 1737139820,
  location: '',
  parentInfo: { isParent: 'NO_ANSWER' },
  phone: '',
  profileImage: 'https://firebasestorage.googleapis.com/v0/b/babalu-476f1.appspot.com/o/app%2Fprofile%2FdefaultProfileImage.png?alt=media',
  pushKitToken: '',
  pushToken: 'e-Uqs7TvWUCcijLM5Ghyh2:APA91bE08CoFiPy7HjDFjATi4h-E--6TeuGphOjabvaMs8D3e9XcZTEmD1dpFz-s9qTOg7pkgnu6bFfNYH1ac8VF8fwBbWKmFcNcYgNx9yQPnyMt_mFsP8E',
  signUpLocation: '',
  username: 'philip',
},
{
  appIdentifier: 'com.littleswaps',
  badgeCount: 0,
  createdAt: 1737139818,
  email: 'philipleesha1@gmail.com',
  firstName: 'Philip1',
  lastName: 'Leesha1',
  lastOnlineTimestamp: 1737139821,
  location: '',
  parentInfo: { isParent: 'NO_ANSWER' },
  phone: '',
  profileImage: 'https://firebasestorage.googleapis.com/v0/b/babalu-476f1.appspot.com/o/app%2Fprofile%2FdefaultProfileImage.png?alt=media',
  pushKitToken: '',
  pushToken: 'e-Uqs7TvWUCcijLM5Ghyh3:APA91bE08CoFiPy7HjDFjATi4h-E--6TeuGphOjabvaMs8D3e9XcZTEmD1dpFz-s9qTOg7pkgnu6bFfNYH1ac8VF8fwBbWKmFcNcYgNx9yQPnyMt_mFsP8F',
  signUpLocation: '',
  username: 'philip1',
},
{
  appIdentifier: 'com.littleswaps',
  badgeCount: 0,
  createdAt: 1737139818,
  email: 'philipleesha2@gmail.com',
  firstName: 'Philip2',
  lastName: 'Leesha2',
  lastOnlineTimestamp: 1737139821,
  location: '',
  parentInfo: { isParent: 'NO_ANSWER' },
  phone: '',
  profileImage: 'https://firebasestorage.googleapis.com/v0/b/babalu-476f1.appspot.com/o/app%2Fprofile%2FdefaultProfileImage.png?alt=media',
  pushKitToken: '',
  pushToken: 'e-Uqs7TvWUCcijLM5Ghyh3:APA91bE08CoFiPy7HjDFjATi4h-E--6TeuGphOjabvaMs8D3e9XcZTEmD1dpFz-s9qTOg7pkgnu6bFfNYH1ac8VF8fwBbWKmFcNcYgNx9yQPnyMt_mFsP8F',
  signUpLocation: '',
  username: 'philip2',
},
{
  appIdentifier: 'com.littleswaps',
  badgeCount: 0,
  createdAt: 1737139818,
  email: 'philipleesha3@gmail.com',
  firstName: 'Philip3',
  lastName: 'Leesha3',
  lastOnlineTimestamp: 1737139821,
  location: '',
  parentInfo: { isParent: 'NO_ANSWER' },
  phone: '',
  profileImage: 'https://firebasestorage.googleapis.com/v0/b/babalu-476f1.appspot.com/o/app%2Fprofile%2FdefaultProfileImage.png?alt=media',
  pushKitToken: '',
  pushToken: 'e-Uqs7TvWUCcijLM5Ghyh3:APA91bE08CoFiPy7HjDFjATi4h-E--6TeuGphOjabvaMs8D3e9XcZTEmD1dpFz-s9qTOg7pkgnu6bFfNYH1ac8VF8fwBbWKmFcNcYgNx9yQPnyMt_mFsP8F',
  signUpLocation: '',
  username: 'philip3',
},
{
  appIdentifier: 'com.littleswaps',
  badgeCount: 0,
  createdAt: 1737139818,
  email: 'philipleesha4@gmail.com',
  firstName: 'Philip4',
  lastName: 'Leesha4',
  lastOnlineTimestamp: 1737139821,
  location: '',
  parentInfo: { isParent: 'NO_ANSWER' },
  phone: '',
  profileImage: 'https://firebasestorage.googleapis.com/v0/b/babalu-476f1.appspot.com/o/app%2Fprofile%2FdefaultProfileImage.png?alt=media',
  pushKitToken: '',
  pushToken: 'e-Uqs7TvWUCcijLM5Ghyh3:APA91bE08CoFiPy7HjDFjATi4h-E--6TeuGphOjabvaMs8D3e9XcZTEmD1dpFz-s9qTOg7pkgnu6bFfNYH1ac8VF8fwBbWKmFcNcYgNx9yQPnyMt_mFsP8F',
  signUpLocation: '',
  username: 'philip4',
},
{
  appIdentifier: 'com.littleswaps',
  badgeCount: 0,
  createdAt: 1737139818,
  email: 'philipleesha5@gmail.com',
  firstName: 'Philip5',
  lastName: 'Leesha5',
  lastOnlineTimestamp: 1737139821,
  location: '',
  parentInfo: { isParent: 'NO_ANSWER' },
  phone: '',
  profileImage: 'https://firebasestorage.googleapis.com/v0/b/babalu-476f1.appspot.com/o/app%2Fprofile%2FdefaultProfileImage.png?alt=media',
  pushKitToken: '',
  pushToken: 'e-Uqs7TvWUCcijLM5Ghyh3:APA91bE08CoFiPy7HjDFjATi4h-E--6TeuGphOjabvaMs8D3e9XcZTEmD1dpFz-s9qTOg7pkgnu6bFfNYH1ac8VF8fwBbWKmFcNcYgNx9yQPnyMt_mFsP8F',
  signUpLocation: '',
  username: 'philip5',
},
{
  appIdentifier: 'com.littleswaps',
  badgeCount: 0,
  createdAt: 1737139818,
  email: 'philipleesha6@gmail.com',
  firstName: 'Philip6',
  lastName: 'Leesha6',
  lastOnlineTimestamp: 1737139821,
  location: '',
  parentInfo: { isParent: 'NO_ANSWER' },
  phone: '',
  profileImage: 'https://firebasestorage.googleapis.com/v0/b/babalu-476f1.appspot.com/o/app%2Fprofile%2FdefaultProfileImage.png?alt=media',
  pushKitToken: '',
  pushToken: 'e-Uqs7TvWUCcijLM5Ghyh3:APA91bE08CoFiPy7HjDFjATi4h-E--6TeuGphOjabvaMs8D3e9XcZTEmD1dpFz-s9qTOg7pkgnu6bFfNYH1ac8VF8fwBbWKmFcNcYgNx9yQPnyMt_mFsP8F',
  signUpLocation: '',
  username: 'philip6',
},
{
  appIdentifier: 'com.littleswaps',
  badgeCount: 0,
  createdAt: 1737139818,
  email: 'philipleesha7@gmail.com',
  firstName: 'Philip7',
  lastName: 'Leesha7',
  lastOnlineTimestamp: 1737139821,
  location: '',
  parentInfo: { isParent: 'NO_ANSWER' },
  phone: '',
  profileImage: 'https://firebasestorage.googleapis.com/v0/b/babalu-476f1.appspot.com/o/app%2Fprofile%2FdefaultProfileImage.png?alt=media',
  pushKitToken: '',
  pushToken: 'e-Uqs7TvWUCcijLM5Ghyh3:APA91bE08CoFiPy7HjDFjATi4h-E--6TeuGphOjabvaMs8D3e9XcZTEmD1dpFz-s9qTOg7pkgnu6bFfNYH1ac8VF8fwBbWKmFcNcYgNx9yQPnyMt_mFsP8F',
  signUpLocation: '',
  username: 'philip7',
},
{
  appIdentifier: 'com.littleswaps',
  badgeCount: 0,
  createdAt: 1737139818,
  email: 'philipleesha8@gmail.com',
  firstName: 'Philip8',
  lastName: 'Leesha8',
  lastOnlineTimestamp: 1737139821,
  location: '',
  parentInfo: { isParent: 'NO_ANSWER' },
  phone: '',
  profileImage: 'https://firebasestorage.googleapis.com/v0/b/babalu-476f1.appspot.com/o/app%2Fprofile%2FdefaultProfileImage.png?alt=media',
  pushKitToken: '',
  pushToken: 'e-Uqs7TvWUCcijLM5Ghyh3:APA91bE08CoFiPy7HjDFjATi4h-E--6TeuGphOjabvaMs8D3e9XcZTEmD1dpFz-s9qTOg7pkgnu6bFfNYH1ac8VF8fwBbWKmFcNcYgNx9yQPnyMt_mFsP8F',
  signUpLocation: '',
  username: 'philip8',
},
{
  appIdentifier: 'com.littleswaps',
  badgeCount: 0,
  createdAt: 1737139818,
  email: 'philipleesha9@gmail.com',
  firstName: 'Philip9',
  lastName: 'Leesha9',
  lastOnlineTimestamp: 1737139821,
  location: '',
  parentInfo: { isParent: 'NO_ANSWER' },
  phone: '',
  profileImage: 'https://firebasestorage.googleapis.com/v0/b/babalu-476f1.appspot.com/o/app%2Fprofile%2FdefaultProfileImage.png?alt=media',
  pushKitToken: '',
  pushToken: 'e-Uqs7TvWUCcijLM5Ghyh3:APA91bE08CoFiPy7HjDFjATi4h-E--6TeuGphOjabvaMs8D3e9XcZTEmD1dpFz-s9qTOg7pkgnu6bFfNYH1ac8VF8fwBbWKmFcNcYgNx9yQPnyMt_mFsP8F',
  signUpLocation: '',
  username: 'philip9',
},
{
  appIdentifier: 'com.littleswaps',
  badgeCount: 0,
  createdAt: 1737139818,
  email: 'philipleesha10@gmail.com',
  firstName: 'Philip10',
  lastName: 'Leesha10',
  lastOnlineTimestamp: 1737139821,
  location: '',
  parentInfo: { isParent: 'NO_ANSWER' },
  phone: '',
  profileImage: 'https://firebasestorage.googleapis.com/v0/b/babalu-476f1.appspot.com/o/app%2Fprofile%2FdefaultProfileImage.png?alt=media',
  pushKitToken: '',
  pushToken: 'e-Uqs7TvWUCcijLM5Ghyh3:APA91bE08CoFiPy7HjDFjATi4h-E--6TeuGphOjabvaMs8D3e9XcZTEmD1dpFz-s9qTOg7pkgnu6bFfNYH1ac8VF8fwBbWKmFcNcYgNx9yQPnyMt_mFsP8F',
  signUpLocation: '',
  username: 'philip10',
},
{
  appIdentifier: 'com.littleswaps',
  badgeCount: 0,
  createdAt: 1737139818,
  email: 'philipleesha11@gmail.com',
  firstName: 'Philip11',
  lastName: 'Leesha11',
  lastOnlineTimestamp: 1737139821,
  location: '',
  parentInfo: { isParent: 'NO_ANSWER' },
  phone: '',
  profileImage: 'https://firebasestorage.googleapis.com/v0/b/babalu-476f1.appspot.com/o/app%2Fprofile%2FdefaultProfileImage.png?alt=media',
  pushKitToken: '',
  pushToken: 'e-Uqs7TvWUCcijLM5Ghyh3:APA91bE08CoFiPy7HjDFjATi4h-E--6TeuGphOjabvaMs8D3e9XcZTEmD1dpFz-s9qTOg7pkgnu6bFfNYH1ac8VF8fwBbWKmFcNcYgNx9yQPnyMt_mFsP8F',
  signUpLocation: '',
  username: 'philip11',
},
{
  appIdentifier: 'com.littleswaps',
  badgeCount: 0,
  createdAt: 1737139818,
  email: 'philipleesha12@gmail.com',
  firstName: 'Philip12',
  lastName: 'Leesha12',
  lastOnlineTimestamp: 1737139821,
  location: '',
  parentInfo: { isParent: 'NO_ANSWER' },
  phone: '',
  profileImage: 'https://firebasestorage.googleapis.com/v0/b/babalu-476f1.appspot.com/o/app%2Fprofile%2FdefaultProfileImage.png?alt=media',
  pushKitToken: '',
  pushToken: 'e-Uqs7TvWUCcijLM5Ghyh3:APA91bE08CoFiPy7HjDFjATi4h-E--6TeuGphOjabvaMs8D3e9XcZTEmD1dpFz-s9qTOg7pkgnu6bFfNYH1ac8VF8fwBbWKmFcNcYgNx9yQPnyMt_mFsP8F',
  signUpLocation: '',
  username: 'philip12',
},
{
  appIdentifier: 'com.littleswaps',
  badgeCount: 0,
  createdAt: 1737139818,
  email: 'philipleesha13@gmail.com',
  firstName: 'Philip13',
  lastName: 'Leesha13',
  lastOnlineTimestamp: 1737139821,
  location: '',
  parentInfo: { isParent: 'NO_ANSWER' },
  phone: '',
  profileImage: 'https://firebasestorage.googleapis.com/v0/b/babalu-476f1.appspot.com/o/app%2Fprofile%2FdefaultProfileImage.png?alt=media',
  pushKitToken: '',
  pushToken: 'e-Uqs7TvWUCcijLM5Ghyh3:APA91bE08CoFiPy7HjDFjATi4h-E--6TeuGphOjabvaMs8D3e9XcZTEmD1dpFz-s9qTOg7pkgnu6bFfNYH1ac8VF8fwBbWKmFcNcYgNx9yQPnyMt_mFsP8F',
  signUpLocation: '',
  username: 'philip13',
},
{
  appIdentifier: 'com.littleswaps',
  badgeCount: 0,
  createdAt: 1737139818,
  email: 'philipleesha14@gmail.com',
  firstName: 'Philip14',
  lastName: 'Leesha14',
  lastOnlineTimestamp: 1737139821,
  location: '',
  parentInfo: { isParent: 'NO_ANSWER' },
  phone: '',
  profileImage: 'https://firebasestorage.googleapis.com/v0/b/babalu-476f1.appspot.com/o/app%2Fprofile%2FdefaultProfileImage.png?alt=media',
  pushKitToken: '',
  pushToken: 'e-Uqs7TvWUCcijLM5Ghyh3:APA91bE08CoFiPy7HjDFjATi4h-E--6TeuGphOjabvaMs8D3e9XcZTEmD1dpFz-s9qTOg7pkgnu6bFfNYH1ac8VF8fwBbWKmFcNcYgNx9yQPnyMt_mFsP8F',
  signUpLocation: '',
  username: 'philip14',
},]