module.exports = [{
  appIdentifier: 'com.littleswaps',
  badgeCount: 0,
  createdAt: 1737139817,
  email: 'philipleesha@gmail.com',
  firstName: 'Philip',
  lastName: 'Leesha',
  lastOnlineTimestamp: 1737139820,
  location: '',
  parentInfo: { isParent: 'NO_ANSWER' },
  phone: '',
  profileImage: 'https://firebasestorage.googleapis.com/v0/b/babalu-476f1.appspot.com/o/app%2Fprofile%2FdefaultProfileImage.png?alt=media',
  pushKitToken: '',
  pushToken: 'e-Uqs7TvWUCcijLM5Ghyh2:APA91bE08CoFiPy7HjDFjATi4h-E--6TeuGphOjabvaMs8D3e9XcZTEmD1dpFz-s9qTOg7pkgnu6bFfNYH1ac8VF8fwBbWKmFcNcYgNx9yQPnyMt_mFsP8E',
  signUpLocation: '',
  username: 'philip',
  discountCodesUsed: ['ONETIMEUSE10']
},
{
  appIdentifier: 'com.littleswaps',
  badgeCount: 0,
  createdAt: 1737139818,
  email: 'philipleesha1@gmail.com',
  firstName: 'Philip1',
  lastName: 'Leesha1',
  lastOnlineTimestamp: 1737139821,
  location: '',
  parentInfo: { isParent: 'NO_ANSWER' },
  phone: '',
  profileImage: 'https://firebasestorage.googleapis.com/v0/b/babalu-476f1.appspot.com/o/app%2Fprofile%2FdefaultProfileImage.png?alt=media',
  pushKitToken: '',
  pushToken: 'e-Uqs7TvWUCcijLM5Ghyh3:APA91bE08CoFiPy7HjDFjATi4h-E--6TeuGphOjabvaMs8D3e9XcZTEmD1dpFz-s9qTOg7pkgnu6bFfNYH1ac8VF8fwBbWKmFcNcYgNx9yQPnyMt_mFsP8F',
  signUpLocation: '',
  username: 'philip1',
  discountCodesUsed: ['ONETIMEUSE10'],
},
{
  appIdentifier: 'com.littleswaps',
  badgeCount: 0,
  createdAt: 1737139818,
  email: 'philipleesha2@gmail.com',
  firstName: 'Philip2',
  lastName: 'Leesha2',
  lastOnlineTimestamp: 1737139821,
  location: '',
  parentInfo: { isParent: 'NO_ANSWER' },
  phone: '',
  profileImage: 'https://firebasestorage.googleapis.com/v0/b/babalu-476f1.appspot.com/o/app%2Fprofile%2FdefaultProfileImage.png?alt=media',
  pushKitToken: '',
  pushToken: 'e-Uqs7TvWUCcijLM5Ghyh3:APA91bE08CoFiPy7HjDFjATi4h-E--6TeuGphOjabvaMs8D3e9XcZTEmD1dpFz-s9qTOg7pkgnu6bFfNYH1ac8VF8fwBbWKmFcNcYgNx9yQPnyMt_mFsP8F',
  signUpLocation: '',
  username: 'philip2',
  discountCodesUsed: ['ONETIMEUSE10'],
},
{
  appIdentifier: 'com.littleswaps',
  badgeCount: 0,
  createdAt: 1737139818,
  email: 'philipleesha3@gmail.com',
  firstName: 'Philip3',
  lastName: 'Leesha3',
  lastOnlineTimestamp: 1737139821,
  location: '',
  parentInfo: { isParent: 'NO_ANSWER' },
  phone: '',
  profileImage: 'https://firebasestorage.googleapis.com/v0/b/babalu-476f1.appspot.com/o/app%2Fprofile%2FdefaultProfileImage.png?alt=media',
  pushKitToken: '',
  pushToken: 'e-Uqs7TvWUCcijLM5Ghyh3:APA91bE08CoFiPy7HjDFjATi4h-E--6TeuGphOjabvaMs8D3e9XcZTEmD1dpFz-s9qTOg7pkgnu6bFfNYH1ac8VF8fwBbWKmFcNcYgNx9yQPnyMt_mFsP8F',
  signUpLocation: '',
  username: 'philip3',
  discountCodesUsed: ['ONETIMEUSE10'],
},
{
  appIdentifier: 'com.littleswaps',
  badgeCount: 0,
  createdAt: 1737139818,
  email: 'philipleesha4@gmail.com',
  firstName: 'Philip4',
  lastName: 'Leesha4',
  lastOnlineTimestamp: 1737139821,
  location: '',
  parentInfo: { isParent: 'NO_ANSWER' },
  phone: '',
  profileImage: 'https://firebasestorage.googleapis.com/v0/b/babalu-476f1.appspot.com/o/app%2Fprofile%2FdefaultProfileImage.png?alt=media',
  pushKitToken: '',
  pushToken: 'e-Uqs7TvWUCcijLM5Ghyh3:APA91bE08CoFiPy7HjDFjATi4h-E--6TeuGphOjabvaMs8D3e9XcZTEmD1dpFz-s9qTOg7pkgnu6bFfNYH1ac8VF8fwBbWKmFcNcYgNx9yQPnyMt_mFsP8F',
  signUpLocation: '',
  username: 'philip4',
  discountCodesUsed: ['ONETIMEUSE10'],
},
{
  appIdentifier: 'com.littleswaps',
  badgeCount: 0,
  createdAt: 1737139818,
  email: 'philipleesha5@gmail.com',
  firstName: 'Philip5',
  lastName: 'Leesha5',
  lastOnlineTimestamp: 1737139821,
  location: '',
  parentInfo: { isParent: 'NO_ANSWER' },
  phone: '',
  profileImage: 'https://firebasestorage.googleapis.com/v0/b/babalu-476f1.appspot.com/o/app%2Fprofile%2FdefaultProfileImage.png?alt=media',
  pushKitToken: '',
  pushToken: 'e-Uqs7TvWUCcijLM5Ghyh3:APA91bE08CoFiPy7HjDFjATi4h-E--6TeuGphOjabvaMs8D3e9XcZTEmD1dpFz-s9qTOg7pkgnu6bFfNYH1ac8VF8fwBbWKmFcNcYgNx9yQPnyMt_mFsP8F',
  signUpLocation: '',
  username: 'philip5',
  discountCodesUsed: ['ONETIMEUSE10'],
},
{
  appIdentifier: 'com.littleswaps',
  badgeCount: 0,
  createdAt: 1737139818,
  email: 'philipleesha6@gmail.com',
  firstName: 'Philip6',
  lastName: 'Leesha6',
  lastOnlineTimestamp: 1737139821,
  location: '',
  parentInfo: { isParent: 'NO_ANSWER' },
  phone: '',
  profileImage: 'https://firebasestorage.googleapis.com/v0/b/babalu-476f1.appspot.com/o/app%2Fprofile%2FdefaultProfileImage.png?alt=media',
  pushKitToken: '',
  pushToken: 'e-Uqs7TvWUCcijLM5Ghyh3:APA91bE08CoFiPy7HjDFjATi4h-E--6TeuGphOjabvaMs8D3e9XcZTEmD1dpFz-s9qTOg7pkgnu6bFfNYH1ac8VF8fwBbWKmFcNcYgNx9yQPnyMt_mFsP8F',
  signUpLocation: '',
  username: 'philip6',
  discountCodesUsed: ['ONETIMEUSE10'],
},
{
  appIdentifier: 'com.littleswaps',
  badgeCount: 0,
  createdAt: 1737139818,
  email: 'philipleesha7@gmail.com',
  firstName: 'Philip7',
  lastName: 'Leesha7',
  lastOnlineTimestamp: 1737139821,
  location: '',
  parentInfo: { isParent: 'NO_ANSWER' },
  phone: '',
  profileImage: 'https://firebasestorage.googleapis.com/v0/b/babalu-476f1.appspot.com/o/app%2Fprofile%2FdefaultProfileImage.png?alt=media',
  pushKitToken: '',
  pushToken: 'e-Uqs7TvWUCcijLM5Ghyh3:APA91bE08CoFiPy7HjDFjATi4h-E--6TeuGphOjabvaMs8D3e9XcZTEmD1dpFz-s9qTOg7pkgnu6bFfNYH1ac8VF8fwBbWKmFcNcYgNx9yQPnyMt_mFsP8F',
  signUpLocation: '',
  username: 'philip7',
  discountCodesUsed: ['ONETIMEUSE10'],
},
{
  appIdentifier: 'com.littleswaps',
  badgeCount: 0,
  createdAt: 1737139818,
  email: 'philipleesha8@gmail.com',
  firstName: 'Philip8',
  lastName: 'Leesha8',
  lastOnlineTimestamp: 1737139821,
  location: '',
  parentInfo: { isParent: 'NO_ANSWER' },
  phone: '',
  profileImage: 'https://firebasestorage.googleapis.com/v0/b/babalu-476f1.appspot.com/o/app%2Fprofile%2FdefaultProfileImage.png?alt=media',
  pushKitToken: '',
  pushToken: 'e-Uqs7TvWUCcijLM5Ghyh3:APA91bE08CoFiPy7HjDFjATi4h-E--6TeuGphOjabvaMs8D3e9XcZTEmD1dpFz-s9qTOg7pkgnu6bFfNYH1ac8VF8fwBbWKmFcNcYgNx9yQPnyMt_mFsP8F',
  signUpLocation: '',
  username: 'philip8',
  discountCodesUsed: ['ONETIMEUSE10'],
},
{
  appIdentifier: 'com.littleswaps',
  badgeCount: 0,
  createdAt: 1737139818,
  email: 'philipleesha9@gmail.com',
  firstName: 'Philip9',
  lastName: 'Leesha9',
  lastOnlineTimestamp: 1737139821,
  location: '',
  parentInfo: { isParent: 'NO_ANSWER' },
  phone: '',
  profileImage: 'https://firebasestorage.googleapis.com/v0/b/babalu-476f1.appspot.com/o/app%2Fprofile%2FdefaultProfileImage.png?alt=media',
  pushKitToken: '',
  pushToken: 'e-Uqs7TvWUCcijLM5Ghyh3:APA91bE08CoFiPy7HjDFjATi4h-E--6TeuGphOjabvaMs8D3e9XcZTEmD1dpFz-s9qTOg7pkgnu6bFfNYH1ac8VF8fwBbWKmFcNcYgNx9yQPnyMt_mFsP8F',
  signUpLocation: '',
  username: 'philip9',
  discountCodesUsed: ['ONETIMEUSE10'],
},
{
  appIdentifier: 'com.littleswaps',
  badgeCount: 0,
  createdAt: 1737139818,
  email: 'philipleesha10@gmail.com',
  firstName: 'Philip10',
  lastName: 'Leesha10',
  lastOnlineTimestamp: 1737139821,
  location: '',
  parentInfo: { isParent: 'NO_ANSWER' },
  phone: '',
  profileImage: 'https://firebasestorage.googleapis.com/v0/b/babalu-476f1.appspot.com/o/app%2Fprofile%2FdefaultProfileImage.png?alt=media',
  pushKitToken: '',
  pushToken: 'e-Uqs7TvWUCcijLM5Ghyh3:APA91bE08CoFiPy7HjDFjATi4h-E--6TeuGphOjabvaMs8D3e9XcZTEmD1dpFz-s9qTOg7pkgnu6bFfNYH1ac8VF8fwBbWKmFcNcYgNx9yQPnyMt_mFsP8F',
  signUpLocation: '',
  username: 'philip10',
  discountCodesUsed: ['ONETIMEUSE10'],
},
{
  appIdentifier: 'com.littleswaps',
  badgeCount: 0,
  createdAt: 1737139818,
  email: 'philipleesha11@gmail.com',
  firstName: 'Philip11',
  lastName: 'Leesha11',
  lastOnlineTimestamp: 1737139821,
  location: '',
  parentInfo: { isParent: 'NO_ANSWER' },
  phone: '',
  profileImage: 'https://firebasestorage.googleapis.com/v0/b/babalu-476f1.appspot.com/o/app%2Fprofile%2FdefaultProfileImage.png?alt=media',
  pushKitToken: '',
  pushToken: 'e-Uqs7TvWUCcijLM5Ghyh3:APA91bE08CoFiPy7HjDFjATi4h-E--6TeuGphOjabvaMs8D3e9XcZTEmD1dpFz-s9qTOg7pkgnu6bFfNYH1ac8VF8fwBbWKmFcNcYgNx9yQPnyMt_mFsP8F',
  signUpLocation: '',
  username: 'philip11',
  discountCodesUsed: ['ONETIMEUSE10'],
},
{
  appIdentifier: 'com.littleswaps',
  badgeCount: 0,
  createdAt: 1737139818,
  email: 'philipleesha12@gmail.com',
  firstName: 'Philip12',
  lastName: 'Leesha12',
  lastOnlineTimestamp: 1737139821,
  location: '',
  parentInfo: { isParent: 'NO_ANSWER' },
  phone: '',
  profileImage: 'https://firebasestorage.googleapis.com/v0/b/babalu-476f1.appspot.com/o/app%2Fprofile%2FdefaultProfileImage.png?alt=media',
  pushKitToken: '',
  pushToken: 'e-Uqs7TvWUCcijLM5Ghyh3:APA91bE08CoFiPy7HjDFjATi4h-E--6TeuGphOjabvaMs8D3e9XcZTEmD1dpFz-s9qTOg7pkgnu6bFfNYH1ac8VF8fwBbWKmFcNcYgNx9yQPnyMt_mFsP8F',
  signUpLocation: '',
  username: 'philip12',
  discountCodesUsed: ['ONETIMEUSE10'],
},
{
  appIdentifier: 'com.littleswaps',
  badgeCount: 0,
  createdAt: 1737139818,
  email: 'philipleesha13@gmail.com',
  firstName: 'Philip13',
  lastName: 'Leesha13',
  lastOnlineTimestamp: 1737139821,
  location: '',
  parentInfo: { isParent: 'NO_ANSWER' },
  phone: '',
  profileImage: 'https://firebasestorage.googleapis.com/v0/b/babalu-476f1.appspot.com/o/app%2Fprofile%2FdefaultProfileImage.png?alt=media',
  pushKitToken: '',
  pushToken: 'e-Uqs7TvWUCcijLM5Ghyh3:APA91bE08CoFiPy7HjDFjATi4h-E--6TeuGphOjabvaMs8D3e9XcZTEmD1dpFz-s9qTOg7pkgnu6bFfNYH1ac8VF8fwBbWKmFcNcYgNx9yQPnyMt_mFsP8F',
  signUpLocation: '',
  username: 'philip13',
  discountCodesUsed: ['ONETIMEUSE10'],
},
{
  appIdentifier: 'com.littleswaps',
  badgeCount: 0,
  createdAt: 1737139818,
  email: 'philipleesha14@gmail.com',
  firstName: 'Philip14',
  lastName: 'Leesha14',
  lastOnlineTimestamp: 1737139821,
  location: '',
  parentInfo: { isParent: 'NO_ANSWER' },
  phone: '',
  profileImage: 'https://firebasestorage.googleapis.com/v0/b/babalu-476f1.appspot.com/o/app%2Fprofile%2FdefaultProfileImage.png?alt=media',
  pushKitToken: '',
  pushToken: 'e-Uqs7TvWUCcijLM5Ghyh3:APA91bE08CoFiPy7HjDFjATi4h-E--6TeuGphOjabvaMs8D3e9XcZTEmD1dpFz-s9qTOg7pkgnu6bFfNYH1ac8VF8fwBbWKmFcNcYgNx9yQPnyMt_mFsP8F',
  signUpLocation: '',
  username: 'philip14',
  discountCodesUsed: ['ONETIMEUSE10'],
},
{
  address: {
    street: "195 N Bedford Rd A",
    street2: "",
    city: "Mt Kisco",
    state: "NY",
    zip: "10549",
    country: 'US',
  },
  appIdentifier: "com.littleswaps",
  badgeCount: 0,
  createdAt: 1732031021,
  description: "Instructions for pickup, and drop off: Park your vehicle at the designated Drive Up parking spaces and we’ll bring them out to you when you arrive.",
  email: "target@littleswaps.com",
  firstName: "Target - Forest Hill",
  followers: 0,
  g: {
    geohash: "dr7d6eujy9zu",
    geopoint: {
      latitude: 41.21635,
      longitude: -73.72172
    }
  },
  isSwapSpot: true,
  isSwapSpotActive: true,
  lastName: "",
  lastOnlineTimestamp: 1732505049,
  location: {
    latitude: 41.1983543,
    longitude: -73.712479
  },
  locationName: "Bedford Corners, NY",
  parentInfo: {
    isParent: "NO_ANSWER"
  },
  phoneNumber: "(804) 330-7365",
  profileImage: "https://firebasestorage.googleapis.com/v0/b/babalu-476f1.appspot.com/o/images%2Fprofile%2F8z9QhrNkn6Z7c2RrqQx3bvJ7dgk1.jpg?alt=media&token=4e970acc-1a8e-4997-b9c7-0ca0765dc265",
  profileImageCover: "https://firebasestorage.googleapis.com/v0/b/babalu-476f1.appspot.com/o/app%2Fprofile%2FdefaultProfileImageCover.png?alt=media",
  pushKitToken: "",
  pushToken: "c7O-xLK9TP-xeWkLWKprXe:APA91bGbs33J7afo0UcMOivMbDwy8TEJfBVnttwrcb-t0z2h3zpcCHggdWmnoOenLzmOqsK9TwmJhemRosOh8EXKrKHbWsVUgzpwTqf1rvRE0RWC6JC9V-8",
  signUpLocation: "",
  swapSpotHours: {
    default: {
      monday: {
        open: "9:00 am",
        close: "10:00 pm"
      },
      tuesday: {
        open: "9:00 am",
        close: "10:00 pm"
      },
      wednesday: {
        open: "9:00 am",
        close: "10:00 pm"
      },
      thursday: {
        open: "9:00 am",
        close: "10:00 pm"
      },
      friday: {
        open: "9:00 am",
        close: "10:00 pm"
      },
      saturday: {
        open: "9:00 am",
        close: "10:00 pm"
      },
      sunday: {
        open: "9:00 am",
        close: "6:00 pm"
      },
    }
  },
  swapSpotName: "Target - Forest Hill",
  username: "target8025",
  website: "https://www.target.com"
},]